### ISSUE TITLE
Update test case server starting/stopping

### ISSUE THREAD

**Issue by camros** [nats-io/elixir-nats#28]
This is a total hack for now, there are timing issues starting and stopping the servers.

**Comment by camros** [comment]
The test cases all depend on gnatsd running on various ports/configs vs. starting and stopping servers automagically during the test cases.

See test/run-test-servers.sh, .travis,mL and test/test_helper.exs

**Comment by mceaglens** [comment]
Comments?
@camros?

**Comment by ColinSullivan1** [comment]
Thank you all for using NATS!  Note that this client has largely been unmaintained and so has been deprecated.  Moving forward we suggest you migrate to the [nats.ex](https://github.com/nats-io/nats.ex) client which will be actively maintained.  We'll keep this repository public in case you'd prefer to make a copy to maintain yourselves, but hope you'll have a good experience with the new client.  We sincerely apologize for the inconvenience.
