### ISSUE TITLE
Difference in content between github and hex

### ISSUE THREAD

**Issue by mm-tfx** [nats-io/elixir-nats#34]
Hi,

I have an Elixir project and I would like to use this Elixir Nats client.
So I have updated mix.exs file with the line given on the Hex i.e. {:nats, "~> 0.1.4", hex: :natsio}
However I would like to use this client in the supervision structure and hence I need the name for the Gen Server. To do so I need then update files inside Deps directory inside my Elixir project.
To avoid this I decided to download source code to my repo (using git subtree) and change mix.exs in my Elixir project.
But when I pulled master I have encountered some performance issues, then I decided to check 0.1.4-alpha tag from Github. But now I cannot compile my main project because of changes in functions names.

My main question would be what is the connection between Github and Hex?
Maybe this sound strange but I would like to know which version is which?

BTW Checking Docs for natsio on Hex I can see version 0.1.5 while all other information seems to be about 0.1.4

**Comment by petemiron** [comment]
@mm-tfx Do you have any more details on your performance issue? I'm going to create a separate issue and get the new version upgrade in hex. Let me know if you can share more details on the performance issue or if you resolved it by staying on 0.1.4. Thanks!

**Comment by petemiron** [comment]
Closing issue. Updated elixir to 0.1.5.
